// Copies the art and sounds listed in the content package's assets.catalog.json
// from the purchased packs into public/assets, trims the padded sound files, and
// records a fingerprint of every shipped file in assets.lock.json.
//
//   npm run sync-art            copy/update files and remove unlisted ones
//   npm run sync-art -- --check only report differences, change nothing
//
// The packs themselves are never modified.

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = path.join(root, 'src', 'content', process.env.CONTENT_PACKAGE || 'starter-adventure');
const catalogPath = path.join(contentDir, 'assets.catalog.json');
const lockPath = path.join(contentDir, 'assets.lock.json');
const publicDir = path.join(root, 'public');
const checkOnly = process.argv.includes('--check');

const catalog = JSON.parse(readFileSync(catalogPath, 'utf8'));

export function sha256(file) {
  return createHash('sha256').update(readFileSync(file)).digest('hex');
}

function walk(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((name) => {
    const full = path.join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

function hasFfmpeg() {
  try {
    execFileSync('ffmpeg', ['-version'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function trimAudio(source, target, seconds) {
  // Mono, 22.05 kHz, 16-bit PCM WAV: small, and every browser can decode it.
  execFileSync('ffmpeg', [
    '-y', '-v', 'error', '-i', source,
    '-t', String(seconds),
    '-af', `afade=t=out:st=${Math.max(0, seconds - 0.08).toFixed(2)}:d=0.08`,
    '-ac', '1', '-ar', '22050', '-c:a', 'pcm_s16le', target
  ]);
}

const ffmpeg = hasFfmpeg();
const oldLock = existsSync(lockPath) ? JSON.parse(readFileSync(lockPath, 'utf8')) : { files: {} };
const lock = { schemaVersion: 1, note: 'Generated by scripts/sync-art.mjs. Do not edit by hand.', files: {} };
const problems = [];
let changed = 0;

for (const entry of catalog.files) {
  const pack = catalog.packs[entry.pack];
  if (!pack) {
    problems.push(`${entry.path}: unknown pack "${entry.pack}"`);
    continue;
  }
  const source = path.join(root, pack.folder, entry.source);
  const target = path.join(publicDir, entry.path);
  const previous = oldLock.files[entry.path];

  if (!existsSync(source)) {
    // The purchased packs are not needed to build: keep the existing copy if it matches the lock.
    if (existsSync(target) && previous && sha256(target) === previous.sha256) {
      lock.files[entry.path] = previous;
      continue;
    }
    problems.push(`${entry.path}: source not found (${path.relative(root, source)})`);
    continue;
  }

  const sourceSha = sha256(source);
  const needsProcess = Boolean(entry.process?.trim);
  const upToDate = existsSync(target) && previous && previous.sourceSha256 === sourceSha
    && previous.process === JSON.stringify(entry.process || null)
    && sha256(target) === previous.sha256;

  if (!upToDate) {
    if (checkOnly) {
      problems.push(`${entry.path}: out of date`);
      continue;
    }
    mkdirSync(path.dirname(target), { recursive: true });
    if (needsProcess) {
      if (!ffmpeg) {
        problems.push(`${entry.path}: needs ffmpeg to trim the sound`);
        continue;
      }
      trimAudio(source, target, entry.process.trim);
    } else {
      copyFileSync(source, target);
    }
    changed += 1;
  }

  lock.files[entry.path] = {
    pack: entry.pack,
    source: path.relative(root, source).split(path.sep).join('/'),
    sourceSha256: sourceSha,
    sha256: sha256(target),
    process: JSON.stringify(entry.process || null),
    bytes: statSync(target).size
  };
}

// Remove shipped files that are no longer listed.
const listed = new Set(catalog.files.map((f) => path.join(publicDir, f.path)));
const stray = walk(path.join(publicDir, 'assets')).filter((file) => !listed.has(file));
for (const file of stray) {
  if (checkOnly) {
    problems.push(`${path.relative(root, file)}: not listed in assets.catalog.json`);
  } else {
    rmSync(file);
    changed += 1;
  }
}
// Clean up empty folders left behind.
function pruneEmpty(dir) {
  if (!existsSync(dir)) return;
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    if (statSync(full).isDirectory()) pruneEmpty(full);
  }
  if (dir !== path.join(publicDir, 'assets') && readdirSync(dir).length === 0) rmSync(dir, { recursive: true });
}
if (!checkOnly) pruneEmpty(path.join(publicDir, 'assets'));

if (!checkOnly) writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);

const total = Object.values(lock.files).reduce((sum, f) => sum + (f.bytes || 0), 0);
if (problems.length) {
  console.error(`sync-art: ${problems.length} problem(s):\n- ${problems.join('\n- ')}`);
  process.exit(1);
}
console.log(`sync-art: ${catalog.files.length} files ready (${(total / 1024).toFixed(0)} KB), ${changed} changed${stray.length ? `, removed ${stray.length} unlisted` : ''}.`);
